name: 🚀 Deploy - Assistente Sustentação (Cloud Run via Docker Hub)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag da imagem (ex: latest ou v1.0.0)"
        required: true
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ==============================================================
      # 📦 Checkout do código
      # ==============================================================
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # ==============================================================
      # 🔐 Login no Docker Hub
      # ==============================================================
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # ==============================================================
      # 🐳 Build e Push da imagem Docker
      # ==============================================================
      - name: Build e Push da imagem Docker
        run: |
          IMAGE="docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/assistente-logs-chat:${{ github.event.inputs.tag }}"
          echo "📦 Construindo imagem: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "✅ Imagem enviada com sucesso para Docker Hub."

      # ==============================================================
      # 🔐 Autenticação com o Google Cloud
      # ==============================================================
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ==============================================================
      # ☁️ Configurar gcloud CLI
      # ==============================================================
      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ==============================================================
      # 🚀 Deploy no Cloud Run usando a imagem do Docker Hub
      # ==============================================================
      - name: Deploy no Cloud Run
        run: |
          SERVICE_NAME="assistente-logs-chat"
          REGION="us-central1"
          IMAGE="docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/assistente-logs-chat:${{ github.event.inputs.tag }}"

          echo "🚀 Iniciando deploy no Cloud Run..."
          echo "📝 Serviço: $SERVICE_NAME"
          echo "📍 Região: $REGION"
          echo "🐳 Imagem: $IMAGE"

          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --allow-unauthenticated \
            --platform managed \
            --port 8080 \
            --min-instances=0 \
            --max-instances=1 \
            --set-env-vars "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"

          echo "✅ Deploy concluído com sucesso."

      # ==============================================================
      # 🌐 Exibir URL pública do serviço
      # ==============================================================
      - name: Mostrar URL do Cloud Run
        run: |
          URL=$(gcloud run services describe assistente-logs-chat \
            --region us-central1 \
            --format='value(status.url)')
          echo "🌍 Serviço disponível em: $URL"

      # ==============================================================
      # 📤 Enviar logs (deploy) para Fluent Bit + Discord
      # ==============================================================
      - name: Enviar logs (deploy) para Fluent Bit e Discord
        if: always()
        env:
          FLUENT_BIT_URL: ${{ secrets.FLUENT_BIT_URL }}
          FLUENT_BIT_AUTH_BA: ${{ secrets.FLUENT_BIT_AUTH_BA }}
          DISCORD_WEBHOOK_PIPELINE: ${{ secrets.DISCORD_WEBHOOK_PIPELINE }}
        run: |
          REPO="${GITHUB_REPOSITORY}"
          WORKFLOW="${GITHUB_WORKFLOW}"
          JOB="${GITHUB_JOB}"
          BRANCH="${GITHUB_REF_NAME}"
          SHA="${GITHUB_SHA}"
          RUN_ID="${GITHUB_RUN_ID}"
          STATUS="${{ job.status }}"
          TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          TIPO_ERRO=$( [ "$STATUS" = "failure" ] && echo "DEPLOY" || echo "INFO" )
          BASE="${REPO}|${WORKFLOW}|${JOB}|${STATUS}|${SHA:0:8}"
          STACK_HASH=$(printf "%s" "$BASE" | shasum -a 256 | awk '{print $1}')

          echo "📡 Enviando logs de deploy para Fluent Bit..."
          curl --location "$FLUENT_BIT_URL" \
            --header 'Content-Type: application/json' \
            --header "Authorization: Basic $FLUENT_BIT_AUTH_BA" \
            --data "{
              \"service\": \"github-actions\",
              \"repo\": \"${REPO}\",
              \"workflow\": \"${WORKFLOW}\",
              \"job\": \"${JOB}\",
              \"status\": \"${STATUS}\",
              \"branch\": \"${BRANCH}\",
              \"autor\": \"${GITHUB_ACTOR}\",
              \"git_sha\": \"${SHA}\",
              \"run_id\": \"${RUN_ID}\",
              \"mensagem_curta\": \"Execução ${STATUS} em ${WORKFLOW}/${JOB}\",
              \"tipo_erro\": \"${TIPO_ERRO}\",
              \"stack_hash\": \"${STACK_HASH}\",
              \"timestamp\": \"${TS}\"
            }"
          echo "✅ Logs enviados com sucesso para Fluent Bit."

          echo "🔔 Enviando notificação para Discord..."
          EMBED_COLOR=$( [ "$STATUS" = "success" ] && echo "5763719" || echo "15548997" )
          COMMIT_URL="https://github.com/${REPO}/actions/runs/${RUN_ID}"

          curl -H "Content-Type: application/json" -X POST "$DISCORD_WEBHOOK_PIPELINE" \
            -d "{
              \"embeds\": [{
                \"title\": \"$( [ "$STATUS" = "success" ] && echo "✅ Deploy - Assistente Sustentação (Cloud Run)" || echo "❌ Falha no Deploy - Assistente Sustentação")\",
                \"color\": ${EMBED_COLOR},
                \"fields\": [
                  {\"name\": \"🧩 Projeto\", \"value\": \"${REPO}\", \"inline\": false},
                  {\"name\": \"🧱 Pipeline\", \"value\": \"${WORKFLOW}\", \"inline\": true},
                  {\"name\": \"💻 Commit\", \"value\": \"${SHA:0:8}\", \"inline\": true},
                  {\"name\": \"🔧 Status\", \"value\": \"${STATUS}\", \"inline\": true},
                  {\"name\": \"🌿 Branch\", \"value\": \"${BRANCH}\", \"inline\": true},
                  {\"name\": \"👤 Iniciado por\", \"value\": \"${GITHUB_ACTOR}\", \"inline\": true},
                  {\"name\": \"📋 Logs\", \"value\": \"[Acessar logs no GitHub](${COMMIT_URL})\", \"inline\": false}
                ],
                \"footer\": {
                  \"text\": \"GitHub Actions - Assistente Sustentação • ${TS}\"
                }
              }]
            }"
          echo "✅ Notificação enviada para Discord com sucesso."
